/* eslint-disable no-console */
/**
 * Скрипт для добавления/обновления регионов БЕЗ очистки базы данных
 * Используйте: node prisma/seed-regions.js
 */
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function seedRegions() {
  const regionsData = [
    {
      code: 'default',
      name: 'Симферополь',
      phone: '+79782944149',
      phoneFormatted: '+7 (978) 294 41 49',
      email: 'info@doorhan-crimea.ru',
      address: 'Симферополь, ул. Примерная, 1',
      addressDescription: 'Офис и выставочный зал',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 9:00-15:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Главный офис',
      isActive: true,
      sortOrder: 0,
    },
    {
      code: 'simferopol',
      name: 'Симферополь',
      phone: '+79782944149',
      phoneFormatted: '+7 (978) 294 41 49',
      email: 'simferopol@doorhan-crimea.ru',
      address: 'Симферополь, ул. Киевская, 15',
      addressDescription: 'Офис и выставочный зал в Симферополе',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 9:00-15:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Симферополь',
      isActive: true,
      sortOrder: 1,
    },
    {
      code: 'kerch',
      name: 'Керчь',
      phone: '+79782944153',
      phoneFormatted: '+7 (978) 294 41 53',
      email: 'kerch@doorhan-crimea.ru',
      address: 'Керчь, ул. Ленина, 12',
      addressDescription: 'Офис в Керчи',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 9:00-15:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Керчь',
      isActive: true,
      sortOrder: 2,
    },
    {
      code: 'evpatoria',
      name: 'Евпатория',
      phone: '+79782944154',
      phoneFormatted: '+7 (978) 294 41 54',
      email: 'evpatoria@doorhan-crimea.ru',
      address: 'Евпатория, ул. Революции, 45',
      addressDescription: 'Офис в Евпатории',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Евпатория',
      isActive: true,
      sortOrder: 3,
    },
    {
      code: 'yalta',
      name: 'Ялта',
      phone: '+79782944150',
      phoneFormatted: '+7 (978) 294 41 50',
      email: 'yalta@doorhan-crimea.ru',
      address: 'Ялта, ул. Набережная, 42',
      addressDescription: 'Офис в Ялте, Южный берег Крыма',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Ялта',
      isActive: true,
      sortOrder: 4,
    },
    {
      code: 'feodosia',
      name: 'Феодосия',
      phone: '+79782944155',
      phoneFormatted: '+7 (978) 294 41 55',
      email: 'feodosia@doorhan-crimea.ru',
      address: 'Феодосия, ул. Галерейная, 8',
      addressDescription: 'Офис в Феодосии',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Феодосия',
      isActive: true,
      sortOrder: 5,
    },
    {
      code: 'sevastopol',
      name: 'Севастополь',
      phone: '+79782944152',
      phoneFormatted: '+7 (978) 294 41 52',
      email: 'sevastopol@doorhan-crimea.ru',
      address: 'Севастополь, ул. Большая Морская, 25',
      addressDescription: 'Офис и выставочный зал в Севастополе',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 9:00-15:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Севастополь',
      isActive: true,
      sortOrder: 6,
    },
    {
      code: 'alushta',
      name: 'Алушта',
      phone: '+79782944151',
      phoneFormatted: '+7 (978) 294 41 51',
      email: 'alushta@doorhan-crimea.ru',
      address: 'Алушта, ул. Ленина, 8',
      addressDescription: 'Офис в Алуште',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Алушта',
      isActive: true,
      sortOrder: 7,
    },
    {
      code: 'dzhankoy',
      name: 'Джанкой',
      phone: '+79782944156',
      phoneFormatted: '+7 (978) 294 41 56',
      email: 'dzhankoy@doorhan-crimea.ru',
      address: 'Джанкой, ул. Ленина, 20',
      addressDescription: 'Офис в Джанкое',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 9:00-15:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Джанкой',
      isActive: true,
      sortOrder: 8,
    },
    {
      code: 'bakhchisaray',
      name: 'Бахчисарай',
      phone: '+79782944157',
      phoneFormatted: '+7 (978) 294 41 57',
      email: 'bakhchisaray@doorhan-crimea.ru',
      address: 'Бахчисарай, ул. Ленина, 15',
      addressDescription: 'Офис в Бахчисарае',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Бахчисарай',
      isActive: true,
      sortOrder: 9,
    },
    {
      code: 'krasnoperekopsk',
      name: 'Красноперекопск',
      phone: '+79782944158',
      phoneFormatted: '+7 (978) 294 41 58',
      email: 'krasnoperekopsk@doorhan-crimea.ru',
      address: 'Красноперекопск, ул. Таврическая, 10',
      addressDescription: 'Офис в Красноперекопске',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 9:00-15:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Красноперекопск',
      isActive: true,
      sortOrder: 10,
    },
    {
      code: 'saki',
      name: 'Саки',
      phone: '+79782944159',
      phoneFormatted: '+7 (978) 294 41 59',
      email: 'saki@doorhan-crimea.ru',
      address: 'Саки, ул. Курортная, 5',
      addressDescription: 'Офис в Саках',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Саки',
      isActive: true,
      sortOrder: 11,
    },
    {
      code: 'armyansk',
      name: 'Армянск',
      phone: '+79782944160',
      phoneFormatted: '+7 (978) 294 41 60',
      email: 'armyansk@doorhan-crimea.ru',
      address: 'Армянск, ул. Гагарина, 8',
      addressDescription: 'Офис в Армянске',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 9:00-15:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Армянск',
      isActive: true,
      sortOrder: 12,
    },
    {
      code: 'sudak',
      name: 'Судак',
      phone: '+79782944161',
      phoneFormatted: '+7 (978) 294 41 61',
      email: 'sudak@doorhan-crimea.ru',
      address: 'Судак, ул. Ленина, 25',
      addressDescription: 'Офис в Судаке',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Судак',
      isActive: true,
      sortOrder: 13,
    },
    {
      code: 'belogorsk',
      name: 'Белогорск',
      phone: '+79782944162',
      phoneFormatted: '+7 (978) 294 41 62',
      email: 'belogorsk@doorhan-crimea.ru',
      address: 'Белогорск, ул. Ленина, 12',
      addressDescription: 'Офис в Белогорске',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Белогорск',
      isActive: true,
      sortOrder: 14,
    },
    {
      code: 'inkerman',
      name: 'Инкерман',
      phone: '+79782944163',
      phoneFormatted: '+7 (978) 294 41 63',
      email: 'inkerman@doorhan-crimea.ru',
      address: 'Инкерман, ул. Победы, 10',
      addressDescription: 'Офис в Инкермане',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 9:00-15:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Инкерман',
      isActive: true,
      sortOrder: 15,
    },
    {
      code: 'balaklava',
      name: 'Балаклава',
      phone: '+79782944164',
      phoneFormatted: '+7 (978) 294 41 64',
      email: 'balaklava@doorhan-crimea.ru',
      address: 'Балаклава, ул. Назукина, 5',
      addressDescription: 'Офис в Балаклаве',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Балаклава',
      isActive: true,
      sortOrder: 16,
    },
    {
      code: 'shchelkino',
      name: 'Щёлкино',
      phone: '+79782944165',
      phoneFormatted: '+7 (978) 294 41 65',
      email: 'shchelkino@doorhan-crimea.ru',
      address: 'Щёлкино, ул. Ленина, 8',
      addressDescription: 'Офис в Щёлкино',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Щёлкино',
      isActive: true,
      sortOrder: 17,
    },
    {
      code: 'stary-krym',
      name: 'Старый Крым',
      phone: '+79782944166',
      phoneFormatted: '+7 (978) 294 41 66',
      email: 'stary-krym@doorhan-crimea.ru',
      address: 'Старый Крым, ул. Ленина, 15',
      addressDescription: 'Офис в Старом Крыму',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Старый Крым',
      isActive: true,
      sortOrder: 18,
    },
    {
      code: 'alupka',
      name: 'Алупка',
      phone: '+79782944167',
      phoneFormatted: '+7 (978) 294 41 67',
      email: 'alupka@doorhan-crimea.ru',
      address: 'Алупка, ул. Ленина, 20',
      addressDescription: 'Офис в Алупке',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Алупка',
      isActive: true,
      sortOrder: 19,
    },
    {
      code: 'gurzuf',
      name: 'Гурзуф',
      phone: '+79782944168',
      phoneFormatted: '+7 (978) 294 41 68',
      email: 'gurzuf@doorhan-crimea.ru',
      address: 'Гурзуф, ул. Ленинградская, 10',
      addressDescription: 'Офис в Гурзуфе',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Гурзуф',
      isActive: true,
      sortOrder: 20,
    },
    {
      code: 'simeiz',
      name: 'Симеиз',
      phone: '+79782944169',
      phoneFormatted: '+7 (978) 294 41 69',
      email: 'simeiz@doorhan-crimea.ru',
      address: 'Симеиз, ул. Советская, 5',
      addressDescription: 'Офис в Симеизе',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Симеиз',
      isActive: true,
      sortOrder: 21,
    },
    {
      code: 'foros',
      name: 'Форос',
      phone: '+79782944170',
      phoneFormatted: '+7 (978) 294 41 70',
      email: 'foros@doorhan-crimea.ru',
      address: 'Форос, ул. Терлецкого, 8',
      addressDescription: 'Офис в Форосе',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Форос',
      isActive: true,
      sortOrder: 22,
    },
    {
      code: 'koktebel',
      name: 'Коктебель',
      phone: '+79782944171',
      phoneFormatted: '+7 (978) 294 41 71',
      email: 'koktebel@doorhan-crimea.ru',
      address: 'Коктебель, ул. Ленина, 15',
      addressDescription: 'Офис в Коктебеле',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Коктебель',
      isActive: true,
      sortOrder: 23,
    },
    {
      code: 'livadia',
      name: 'Ливадия',
      phone: '+79782944172',
      phoneFormatted: '+7 (978) 294 41 72',
      email: 'livadia@doorhan-crimea.ru',
      address: 'Ливадия, ул. Батурина, 10',
      addressDescription: 'Офис в Ливадии',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Ливадия',
      isActive: true,
      sortOrder: 24,
    },
    {
      code: 'massandra',
      name: 'Массандра',
      phone: '+79782944173',
      phoneFormatted: '+7 (978) 294 41 73',
      email: 'massandra@doorhan-crimea.ru',
      address: 'Массандра, ул. Стахановская, 5',
      addressDescription: 'Офис в Массандре',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Массандра',
      isActive: true,
      sortOrder: 25,
    },
    {
      code: 'nikita',
      name: 'Никита',
      phone: '+79782944174',
      phoneFormatted: '+7 (978) 294 41 74',
      email: 'nikita@doorhan-crimea.ru',
      address: 'Никита, ул. Набережная, 8',
      addressDescription: 'Офис в Никите',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Никита',
      isActive: true,
      sortOrder: 26,
    },
    {
      code: 'gaspra',
      name: 'Гаспра',
      phone: '+79782944175',
      phoneFormatted: '+7 (978) 294 41 75',
      email: 'gaspra@doorhan-crimea.ru',
      address: 'Гаспра, ул. Ялтинская, 12',
      addressDescription: 'Офис в Гаспре',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Гаспра',
      isActive: true,
      sortOrder: 27,
    },
    {
      code: 'miskhor',
      name: 'Мисхор',
      phone: '+79782944176',
      phoneFormatted: '+7 (978) 294 41 76',
      email: 'miskhor@doorhan-crimea.ru',
      address: 'Мисхор, ул. Алупкинское шоссе, 10',
      addressDescription: 'Офис в Мисхоре',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Мисхор',
      isActive: true,
      sortOrder: 28,
    },
    {
      code: 'partenit',
      name: 'Партенит',
      phone: '+79782944177',
      phoneFormatted: '+7 (978) 294 41 77',
      email: 'partenit@doorhan-crimea.ru',
      address: 'Партенит, ул. Партенитская, 5',
      addressDescription: 'Офис в Партените',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Партенит',
      isActive: true,
      sortOrder: 29,
    },
    {
      code: 'kacha',
      name: 'Кача',
      phone: '+79782944178',
      phoneFormatted: '+7 (978) 294 41 78',
      email: 'kacha@doorhan-crimea.ru',
      address: 'Кача, ул. Ленина, 8',
      addressDescription: 'Офис в Каче',
      workingHours: 'Пн-Пт: 9:00-18:00, Сб: 10:00-16:00',
      workingHoursDescription: 'Воскресенье - выходной',
      officeName: 'Кача',
      isActive: true,
      sortOrder: 30,
    },
  ];

  console.log('Добавление/обновление регионов...');
  
  for (const region of regionsData) {
    const result = await prisma.region.upsert({
      where: { code: region.code },
      update: region,
      create: region,
    });
    console.log(`✓ ${result.code}: ${result.name}`);
  }

  console.log(`\n✅ Обработано регионов: ${regionsData.length}`);
}

async function main() {
  try {
    await seedRegions();
  } catch (error) {
    console.error('Ошибка при добавлении регионов:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();

